[[language]]
name = "go"
formatter = { command = "goimports" }
roots = ["go.mod"]
diagnostic-severity = "Hint"

[[language]]
name = "rust"

[[language]]
name = "typescript"
language-servers = ["eslint", "typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["eslint", "typescript-language-server"]

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = false
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }
