theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
gutters = ["spacer", "diagnostics", "spacer", "diff", "line-numbers", "spacer"]
color-modes = true
cursorline = true
idle-timeout = 50
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.search]
smart-case = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "workspace-diagnostics"]
center = ["file-name"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "total-line-numbers", "file-type", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { q = ":q", w = ":w", c = ":buffer-close", o = ":buffer-close-others"}
"'" = "repeat_last_motion"

[keys.insert]
j = { k = "normal_mode" }
