theme = "catppuccin_mocha"

[editor]
line-number = "relative"
gutters = ["spacer", "diagnostics", "spacer", "diff", "line-numbers", "spacer"]
color-modes = true
cursorline = true
idle-timeout = 50
true-color=true
completion-trigger-len = 1

# [editor.indent-guides]
# render = true
# character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.search]
smart-case = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "workspace-diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "total-line-numbers", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { q = ":q", w = ":w", c = ":buffer-close", o = ":buffer-close-others"}
"'" = "repeat_last_motion"
L = "extend_to_line_end"
H = "extend_to_line_start"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
j = { k = "normal_mode" }
