fg="#CBCCC6"
bg="#212732"
status_bg="#34455A"
border_fg="#70748C"
border_active_fg="#FECB6E"
status_left_bg="#FFA759"

set -g status-style "bg=$status_bg,fg=$fg"
set -g status-right "%A, %B %d %l:%M %p "
set -g status-left ' [#S] '
set -g status-left-length 32
bind-key -n C-t set-option -g status

set -g base-index 1
set -g pane-base-index 1

set-option -g history-limit 500

# update status bar info
set -g status-interval 60
